#!/usr/bin/env python3
"""Build a single-file Obsidian plugin bundle from local CommonJS modules."""
from __future__ import annotations

import argparse
import base64
import hashlib
import json
from pathlib import Path


MODULES = [
    "main.js",
    "brandAssets.js",
    "bundledEngine.js",
    "i18n.js",
    "safety.js",
    "relationTargetResolution.js",
    "agentApi.js",
    "agentAccess.js",
    "engineHealth.js",
    "settings.js",
    "commands.js",
    "graphifyLayer.js",
    "graphifyCore.js",
    "graphifyViews.js",
    "graphifyRuntime.js",
    "linkDiscovery.js",
    "utils.js",
    "settingsStyles.js",
    "settingsLogs.js",
    "settingsFolders.js",
    "relationsStore.js",
    "sidebarView.js",
]


VIRTUAL_AGENT_ACCESS_SOURCES = "agentAccessBundledSources.js"
VIRTUAL_BUNDLED_ENGINE_PAYLOAD = "bundledEnginePayload.js"
ENGINE_DIR_NAME = "understory-graphify-engine"
EXCLUDED_ENGINE_NAMES = {
    ".cache",
    ".env",
    ".git",
    ".pytest_cache",
    ".serena",
    "__pycache__",
    "config.yaml",
}
EXCLUDED_ENGINE_SUFFIXES = {".db", ".pyc", ".sqlite"}


def module_id(filename: str) -> str:
    return "./" + Path(filename).with_suffix("").as_posix()


def include_engine_file(path: Path) -> bool:
    parts = set(path.parts)
    if parts & EXCLUDED_ENGINE_NAMES:
        return False
    return path.suffix.lower() not in EXCLUDED_ENGINE_SUFFIXES


def build_bundled_engine_payload(root_dir: Path) -> dict:
    engine_dir = root_dir / ENGINE_DIR_NAME
    if not engine_dir.exists():
        raise FileNotFoundError(f"Bundled engine directory is missing: {engine_dir}")

    files = []
    for path in sorted(engine_dir.rglob("*")):
        if not path.is_file():
            continue
        relative = path.relative_to(engine_dir)
        if not include_engine_file(relative):
            continue
        data = path.read_bytes()
        files.append({
            "path": relative.as_posix(),
            "contentBase64": base64.b64encode(data).decode("ascii"),
            "sha256": hashlib.sha256(data).hexdigest(),
        })

    required = {
        "api.py",
        "scripts/deploy_graphify.py",
        "requirements.txt",
    }
    included = {file["path"] for file in files}
    missing = sorted(required - included)
    if missing:
        raise FileNotFoundError(f"Bundled engine payload is missing required files: {', '.join(missing)}")

    return {
        "version": 1,
        "engineDirName": ENGINE_DIR_NAME,
        "files": files,
    }


def build_bundle(plugin_dir: Path) -> str:
    blocks: list[str] = []
    for filename in MODULES:
        path = plugin_dir / filename
        if not path.exists():
            raise FileNotFoundError(path)
        source = path.read_text(encoding="utf-8")
        blocks.append(f"{json.dumps(module_id(filename))}: function(module, exports, require) {{\n{source}\n}}")

    root_dir = plugin_dir.parent
    bundled_sources = {
        "agentApiSource": (plugin_dir / "agentApi.js").read_text(encoding="utf-8"),
        "safetySource": (plugin_dir / "safety.js").read_text(encoding="utf-8"),
        "mcpServerSource": (root_dir / "scripts" / "understory-mcp-server.js").read_text(encoding="utf-8"),
    }
    virtual_source = "module.exports = " + json.dumps(bundled_sources, ensure_ascii=False) + ";"
    blocks.append(
        f"{json.dumps(module_id(VIRTUAL_AGENT_ACCESS_SOURCES))}: "
        f"function(module, exports, require) {{\n{virtual_source}\n}}"
    )

    engine_payload_source = "module.exports = " + json.dumps(build_bundled_engine_payload(root_dir), ensure_ascii=False) + ";"
    blocks.append(
        f"{json.dumps(module_id(VIRTUAL_BUNDLED_ENGINE_PAYLOAD))}: "
        f"function(module, exports, require) {{\n{engine_payload_source}\n}}"
    )

    joined = ",\n\n".join(blocks)
    return f"""// Generated by scripts/bundle_obsidian_plugin.py. Do not edit this file directly.
(function() {{
const __rootRequire = typeof require === 'function' ? require : null;
const __modules = {{
{joined}
}};
const __cache = {{}};
function __normalize(id) {{
    if (id.endsWith('.js')) id = id.slice(0, -3);
    id = id.replace(/\\\\/g, '/');
    return id;
}}
function __require(id) {{
    const key = __normalize(id);
    if (Object.prototype.hasOwnProperty.call(__modules, key)) {{
        if (__cache[key]) return __cache[key].exports;
        const module = {{ exports: {{}} }};
        __cache[key] = module;
        __modules[key](module, module.exports, __require);
        return module.exports;
    }}
    if (__rootRequire) return __rootRequire(id);
    throw new Error('Cannot resolve module: ' + id);
}}
const __entry = {{ exports: {{}} }};
__modules['./main'](__entry, __entry.exports, __require);
module.exports = __entry.exports;
}})();
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle obsidian-plugin/*.js into one main.js")
    parser.add_argument("--plugin-dir", default="obsidian-plugin", help="Source plugin directory")
    parser.add_argument("--out", required=True, help="Output main.js path")
    args = parser.parse_args()

    plugin_dir = Path(args.plugin_dir).resolve()
    out = Path(args.out).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_bundle(plugin_dir), encoding="utf-8", newline="\n")
    print(out)


if __name__ == "__main__":
    main()
