#!/usr/bin/env python3
"""Build a single-file Obsidian plugin bundle from local CommonJS modules."""
from __future__ import annotations

import argparse
import json
from pathlib import Path


MODULES = [
    "main.js",
    "i18n.js",
    "safety.js",
    "agentApi.js",
    "engineHealth.js",
    "settings.js",
    "commands.js",
    "graphifyLayer.js",
    "graphifyCore.js",
    "graphifyViews.js",
    "graphifyRuntime.js",
    "linkDiscovery.js",
    "utils.js",
    "settingsStyles.js",
    "settingsLogs.js",
    "settingsFolders.js",
    "relationsStore.js",
    "sidebarView.js",
]


def module_id(filename: str) -> str:
    return "./" + Path(filename).with_suffix("").as_posix()


def build_bundle(plugin_dir: Path) -> str:
    blocks: list[str] = []
    for filename in MODULES:
        path = plugin_dir / filename
        if not path.exists():
            raise FileNotFoundError(path)
        source = path.read_text(encoding="utf-8")
        blocks.append(f"{json.dumps(module_id(filename))}: function(module, exports, require) {{\n{source}\n}}")

    joined = ",\n\n".join(blocks)
    return f"""// Generated by scripts/bundle_obsidian_plugin.py. Do not edit this file directly.
(function() {{
const __rootRequire = typeof require === 'function' ? require : null;
const __modules = {{
{joined}
}};
const __cache = {{}};
function __normalize(id) {{
    if (id.endsWith('.js')) id = id.slice(0, -3);
    id = id.replace(/\\\\/g, '/');
    return id;
}}
function __require(id) {{
    const key = __normalize(id);
    if (Object.prototype.hasOwnProperty.call(__modules, key)) {{
        if (__cache[key]) return __cache[key].exports;
        const module = {{ exports: {{}} }};
        __cache[key] = module;
        __modules[key](module, module.exports, __require);
        return module.exports;
    }}
    if (__rootRequire) return __rootRequire(id);
    throw new Error('Cannot resolve module: ' + id);
}}
const __entry = {{ exports: {{}} }};
__modules['./main'](__entry, __entry.exports, __require);
module.exports = __entry.exports;
}})();
"""


def main() -> None:
    parser = argparse.ArgumentParser(description="Bundle obsidian-plugin/*.js into one main.js")
    parser.add_argument("--plugin-dir", default="obsidian-plugin", help="Source plugin directory")
    parser.add_argument("--out", required=True, help="Output main.js path")
    args = parser.parse_args()

    plugin_dir = Path(args.plugin_dir).resolve()
    out = Path(args.out).resolve()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(build_bundle(plugin_dir), encoding="utf-8", newline="\n")
    print(out)


if __name__ == "__main__":
    main()
